import { Schema } from 'mongoose';

const mixedList = { type: [Schema.Types.Mixed], default: [] };

/** Catalog fields collected by the admin product form. */
export const productCatalogFields = {
  brand: { type: String, default: '', trim: true },
  company: { type: String, default: '', trim: true },
  subscriptionDurations: mixedList,
  subscriptions: mixedList,
  ebookPriceINR: { type: String, default: '' },
  ebookPriceUSD: { type: String, default: '' },
  hasLifetime: { type: Boolean, default: false },
  lifetimePrice: { type: String, default: '' },
  lifetimePriceINR: { type: String, default: '' },
  lifetimePriceUSD: { type: String, default: '' },
  hasMembership: { type: Boolean, default: false },
  membershipPrice: { type: String, default: '' },
  membershipPriceINR: { type: String, default: '' },
  membershipPriceUSD: { type: String, default: '' },
  strikethroughPriceINR: { type: String, default: '' },
  strikethroughPriceUSD: { type: String, default: '' },
  imageUrl: { type: String, default: '' },
  additionalImages: { type: [String], default: [] },
  videoUrl: { type: String, default: '' },
  activationVideoUrl: { type: String, default: '' },
  instagramReels: { type: [String], default: [] },
  driveLink: { type: String, default: '' },
  faqs: mixedList,
  systemRequirements: mixedList,
  reviews: mixedList,
  isDeal: { type: Boolean, default: false },
  dealStartDate: { type: String, default: '' },
  dealStartTime: { type: String, default: '' },
  dealEndDate: { type: String, default: '' },
  dealEndTime: { type: String, default: '' },
  dealEbookPriceINR: { type: String, default: '' },
  dealEbookPriceUSD: { type: String, default: '' },
  dealLifetimePriceINR: { type: String, default: '' },
  dealLifetimePriceUSD: { type: String, default: '' },
  dealMembershipPriceINR: { type: String, default: '' },
  dealMembershipPriceUSD: { type: String, default: '' },
  dealSubscriptionDurations: mixedList,
  dealSubscriptions: mixedList,
  isFreeProduct: { type: Boolean, default: false },
  freeProductStartDate: { type: String, default: '' },
  freeProductStartTime: { type: String, default: '' },
  freeProductEndDate: { type: String, default: '' },
  freeProductEndTime: { type: String, default: '' },
};
